events {
    worker_connections 1024;
}

http {
    # 1. Define the internal backend services (Docker DNS handles the IPs)
    upstream aggregator_backend {
        least_conn;    # Change from round robin to least connections routing to ease back pressure on heavily impacted nodes.
        server aggregator:8080;
    }

    upstream api_backend {
        least_conn;
        server api-server:8081;
    }

    # 2. Define the public-facing server
    server {
        listen 80;

        # 3. Route REST API traffic
        location /status/ {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /machines {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. Route and Upgrade WebSocket traffic (The Senior Move)
        location /telemetry {
            proxy_pass http://aggregator_backend;
            proxy_http_version 1.1;
            # These two headers tell NGINX to allow the TCP connection to stay open
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
